# Generated by Django 6.0.1 on 2026-03-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('emailbody', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('emaildate', models.DateTimeField(auto_now_add=True)),
                ('detected_status', models.CharField(blank=True, max_length=100, null=True)),
                ('APP_ID', models.ForeignKey(db_column='APP_ID', on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'email',
            },
        ),
    ]
