# Generated by Django 6.0.1 on 2026-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.IntegerField(default=0, unique=True)),
                ('APP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('jobrole', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
