# Generated by Django 6.0.1 on 2026-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('U_ID', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
