# Generated by Django 6.0.1 on 2026-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Codeforces_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Leetcode_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
