# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_codeforces_username_user_leetcode_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
