# Generated by Django 6.0.1 on 2026-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('blogtext', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
